exp_name: new_agents_approach
save_path: save/${exp_name}
gui: false
seed: 42
players_number: 5
players:
  -
      name: serg # names must be unique
      role: sherif
      max_hp: 4

  -
      name: andy
      role: renegade
      max_hp: 4

  -
      name: anna
      role: bandit
      max_hp: 4

  -
      name: igor
      role: bandit
      max_hp: 4

  -
      name: john
      role: sherif_assistant
      max_hp: 4

agents:
  # name from players
  serg:
    agent_id: base
    agent_type: base_llm_agent # user_agent dummy_agent base_llm_agent speaking_llm_agent, coop_llm_agent, base_multi_llm_agent coop_multi_llm_agent choice_coop_multi_llm_agent
    context_len: 20
  andy:
    agent_id: base
    agent_type: base_llm_agent
    context_len: 20
  anna:
    agent_id: base
    agent_type: base_llm_agent
    context_len: 20
  igor:
    agent_id: base
    agent_type: base_llm_agent
    context_len: 20
  john:
    agent_id: base
    agent_type: base_llm_agent
    context_len: 20

cards: # base card set
  bang: 25
  beer: 6
  miss: 12
  mustang: 2
  scope: 1
  hottie: 4
  saloon: 1
  gatling: 1
  panic: 4
  indians: 2
  fargo: 1
  stagecoach: 2
  volkanic: 2
  scofield: 3
  remington: 1
  carbine: 1
  winchester: 1

