save_path: save/test
gui: false
seed: 42
players_number: 4
players:
  -
      name: serg # names must be unique
      role: sherif
      max_hp: 4

  -
      name: andy
      role: renegade
      max_hp: 4

  -
      name: anna
      role: bandit
      max_hp: 4

  -
      name: igor
      role: bandit
      max_hp: 4

agents:
  # name from players
  serg:
    agent_type: user_agent
  andy:
    agent_type: user_agent
  anna:
    agent_type: user_agent
  igor:
    agent_type: user_agent

cards: # base card set
  bang: 25
  beer: 6
  miss: 12
  mustang: 2
  scope: 1
  hottie: 4
  saloon: 1
  gatling: 1
  panic: 4
  indians: 2
  fargo: 1
  stagecoach: 2
  volkanic: 2
  scofield: 3
  remington: 1
  carbine: 1
  winchester: 1

